#!/usr/bin/env bash
# This hook is run after every virtualenv is activated.
source "${WORKON_HOME}/env_preinit"

# CLEAR OUT GREMLINS (e.g. ".DS_Store")
# NB. this praxon shouldn't be called "installing"
install_praxon "clear-filesystem-gremlins"

# LOAD THE DEV-ENVIRONMENT FUNCS
load_praxon "88-postinit"

# READ IN THE PASSWORD
install_praxon "password-read"
