#!/usr/bin/env bash
# This hook is run after every virtualenv is activated.
source "${WORKON_HOME}/env_preinit"

# CLEAR OUT GREMLINS (e.g. ".DS_Store")
load_praxon "Install" "clear-filesystem-gremlins"

# LOAD THE DEV-ENVIRONMENT FUNCS
load_praxon "Library" "88-postinit"

# READ IN THE PASSWORD
load_praxon "Install" "password-read"
