#!/usr/bin/env bash
# This hook is run after a new virtualenv is activated.
source "${WORKON_HOME}/env_preinit"

# CREATE INSTANCE FILESYSTEM LAYOUT
install_praxon "create-instance-filesystem"

# PROVISION VIRON
install_praxon "provision-viron"

# WRITE THE PASSWORD
install_praxon "password-write"

# PIP-INSTALL EVERYTHING
install_praxon "provision-cheeseshop"

# INSTALL SOLR
install_praxon "provision-solr-instance"

# PROJECT-LOCAL OPENCV
#install_praxon "provision-opencv-venv"

# PROJECT-LOCAL NODEJS
# NB. cache the `nodeenv` download if possibe
#install_praxon "provision-nodejs-venv"

# PRE-TEMPLATE FILES
install_praxon "project-template-preinit"

# GENERATE PROJECT TEMPLATE
install_praxon "project-template"

# POST-TEMPLATE FILES
install_praxon "project-template-postinit"

# GET RID OF THIS SHIT
echo "+ Trashing installation artifacts ..."
vremove pysqlite2-doc
vremove restkit
vremove socketpool

# CONFIGURE DEV-ENVIRONMENT FUNCTIONS
load_praxon "88-postinit"

# INITIALIZE ALL THE DJANGO THINGS
install_praxon "initialize-django-instance"

# SCHEMATIZE SOLR (using django-haystack)
# AND LINK XML CONFIGS INTO etc/
install_praxon "create-solr-schema-and-etc-links"

echo "+ Cleaning up ..." # LIES!!

# SET UP GIT
install_praxon "initialize-venv-git-repo"

