#!/usr/bin/env bash
# This hook is run before every virtualenv is deactivated.
source "${WORKON_HOME}/env_preinit"

# CLEAR OUT GREMLINS (e.g. ".DS_Store")
load_praxon "Install" "clear-filesystem-gremlins"
