#!/usr/bin/env bash
# This hook is run after every virtualenv is activated.
source "${VIRTUALENVWRAPPER_HOOK_DIR}/env_preinit"

# CLEAR OUT GREMLINS (e.g. ".DS_Store")
load_praxon "clean-filesystem"

# READ IN THE PASSWORD
load_praxon "read-password"

# LOAD THE DEV-ENVIRONMENT FUNCS
load_praxon "venv-functions"
