#!/usr/bin/env bash
# This hook is run after a new virtualenv is activated.
source "${VIRTUALENVWRAPPER_HOOK_DIR}/env_preinit"

# CREATE INSTANCE FILESYSTEM LAYOUT
install_praxon "create-venv-filesystem"

# PROVISION VIRON
install_praxon "provision-viron"

# WRITE THE PASSWORD
install_praxon "write-password"

# PIP-INSTALL EVERYTHING
install_praxon "provision-cheeseshop-venv"

# INSTALL SOLR
install_praxon "provision-solr-venv"

# PROJECT-LOCAL OPENCV
#install_praxon "provision-opencv-venv"

# PROJECT-LOCAL NODEJS
# NB. cache the `nodeenv` download if possibe
install_praxon "provision-nodejs-venv"

# PRE-TEMPLATE FILES
install_praxon "setup-instance-template-preinit"

# GENERATE PROJECT TEMPLATE
install_praxon "setup-instance-template"

# POST-TEMPLATE FILES
install_praxon "setup-instance-template-postinit"

# GET RID OF THIS SHIT
echo "+ Trashing installation artifacts ..."
vremove pysqlite2-doc
vremove restkit
vremove socketpool

# CONFIGURE DEV-ENVIRONMENT FUNCTIONS
load_praxon "venv-functions"

# INITIALIZE ALL THE DJANGO THINGS
install_praxon "setup-instance-django-db"

# SCHEMATIZE SOLR (using django-haystack)
# AND LINK XML CONFIGS INTO etc/
install_praxon "make-solr-etc-files"

echo "+ Cleaning up ..." # LIES!!

# SET UP GIT
install_praxon "initialize-git-repo"

