#!/usr/bin/env bash
# This hook is run before every virtualenv is deactivated.
source "${VIRTUALENVWRAPPER_HOOK_DIR}/env_preinit"

# CLEAN OUT THE GREMLINS (e.g. ".DS_Store")
load_praxon "clean-filesystem"
